
# ============================================================
# MINIMAL HYPRLAND CONFIG - NATURAL SCROLL FIX
# ============================================================



# Monitor
monitor=,preferred,auto,1
#conf
exec-once = hyprpaper
exec-once = ~/.config/hypr/random_wallpaper.sh

#wallpaper
exec-once = swaybg -i /home/pramod/Pictures/wallpapers/a.png -m fill

preload = /home/pramod/Pictures/Pictures/wallpapers/f.jpg
wallpaper = eDP-1, /home/pramod/Pictures/wallpapers/f.jpg

# Startup programs
exec-once = waybar &
exec-once = wofi --show drun &

# ============================================================
# INPUT SETTINGS - NATURAL SCROLL IS HERE
# ============================================================
input {
    kb_layout = us
    follow_mouse = 1
    
    touchpad {
        natural_scroll = true
    }
}

# ============================================================
# GENERAL SETTINGS
# ============================================================
general {
    gaps_in = 7
    gaps_out = 17
    border_size = 4
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(006400ee)
    layout = dwindle
}

decoration = {
        rounding       = 10,
        rounding_power = 2,

# ============================================================
# KEYBINDINGS
# ============================================================
$mainMod = SUPER

bind = $mainMod, Q, exec, kitty
bind = $mainMod, C, killactive,
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, wofi --show drun
bind = $mainMod, M, exit
bind = $mainMod, s, exec, code-oss
bind = $mainMod, W, exec, hyprctl hyprpaper reload ,"$(find ~/Pictures/wallpapers -type f | shuf -n 1)"


# Capture currently active window
bind = $mainMod, PRINT, exec, hyprshot -m window
# Capture the whole screen
bind = , PRINT, exec, hyprshot -m output
# Capture a selected region (freezes screen if hyprpicker is installed)
bind = SHIFT, PRINT, exec, hyprshot -m region --freeze


#Brightness
binde = , XF86MonBrightnessUp, exec, brightnessctl s +5%
binde = , XF86MonBrightnessDown, exec, brightnessctl s 5%-


#volume
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Microphone
bind = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

